version: '3.8'

services:
  db:
    image: postgres:16
    container_name: quizzerando-db
    environment:
      POSTGRES_DB: quizzerando
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
